slug: ff1
name: Final Fantasy (USA)
file: Final Fantasy (USA).nes
sha1: 80ce108fbc066c985d4fb541bd68e9a7c8994feb
credits:
  AstralEsper's game mechanics guide: https://gamefaqs.gamespot.com/nes/522595-final-fantasy/faqs/57009
