# Example map metadata file

slug: smrpg
name: Super Mario RPG - Legend of the Seven Stars (USA)
file: Super Mario RPG - Legend of the Seven Stars (USA).sfc
sha1: a4f7539054c359fe3f360b0e6b72e394439fe9df
