# Example map metadata file

slug: ogrebattle
name: Ogre Battle - The March of the Black Queen (USA)
file: Ogre Battle - The March of the Black Queen (USA).sfc
sha1: cfc45162b91791a61d4260e348ad43cb3b2eca0f
