slug: pokemon-ruby
name: Pokemon Ruby (USA)
file: Pokemon - Ruby Version (USA, Europe) (Rev 2).gba
sha1: 5b64eacf892920518db4ec664e62a086dd5f5bc8
credits:
  Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Main_Page
  Pret: https://github.com/pret/pokeruby/
